baseURL = 'https://dupeiran001.github.io/blog/'
title = "My Blog"
languageCode = 'en-us'
theme = "hello-friend-ng"
paginate = 10

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

# Subtitle for home
homeSubtitle = "Homepage"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = true

# Metadata mostly used in document's head
description = "My homepage"
keywords = "homepage, blog"
images = [""]

[taxonomies]
category = "blog"
tag = "tags"
series = "series"

[languages]
[languages.en]
title = "Hello Friend NG"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[languages.en.params]
subtitle = "A simple theme for Hugo"
readOtherPosts = "Read other posts"
keywords = ""

[languages.en.params.logo]
logoText = "cd $HOME/"
logoHomeLink = "/blog/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
